### ISSUE TITLE
Task 2

### ISSUE THREAD

**Issue by batist73** [dori17/Inspiration#1]
@dori17 

Главная страница:
- Всё же фильтры осущестляют фильтрацию, а не сортировку, то есть надпись "Sort posts by" не совсем логична. При этом, не совсем понятно как они работают. По идее, вам необходимо предоставить возможность для ввода значений для всех трёх параметров.
- Для авторизованного пользователя на ленте постов отображается иконка удаления постов. Такая же иконка есть и на странице редактирования поста. Хотелось бы избежать такого дублирования функциональности. Думаю, стоит оставить её в каком-нибудь одном месте.

**Comment by dori17** [comment]
Можно исправить до восьми? Или это конечный неоспоримый результат за 2
задание?

19 февр. 2018 г. 11:37 ДП пользователь "Anton Grigoriev" <
notifications@github.com> написал:

**Comment by batist73** [comment]
@dori17 
Можно исправлять до дедлайна.

**Comment by dori17** [comment]
Как отметить, чтобы вы посмотрели? Что-то в духе git tag task2UPD?

19 февр. 2018 г. 2:48 ПП пользователь "Anton Grigoriev" <
notifications@github.com> написал:

**Comment by batist73** [comment]
@dori17 
Можно просто оставлять комментарии в Issue.

**Comment by dori17** [comment]
Поправила. Посмотрите, пожалуйста

**Comment by dori17** [comment]
@AntonGrigoriev 
Поправила. Посмотрите, пожалуйста
